import { Inter } from "next/font/google";
import "./globals.css";
import "@/public/Fonts/font.css";
import Head from "next/head";
import Navbar from "@/Components/Navbar";
import Footer from "@/Components/Footer";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons" />
      </Head>
      <body className={inter.className}>
        <header>
          <Navbar />
        </header>
        <main>{children}</main>
        <footer>
          <Footer/>
        </footer>
      </body>
    </html>
  );
}